#pragma once

#define CONFIG_REMOTEBSP_MOTION 1
#define CONFIG_MOTION_MAX_AXES 4
#define CONFIG_MOTION_QUEUE_DEPTH 3
#define CONFIG_MOTION_MIN_LEAD_TIME_US 1000
#define CONFIG_MOTION_TIMER_HZ 100000
#define CONFIG_REMOTE_MAX_PACKET_SIZE 1024
#define CONFIG_REMOTE_CACHE_RESPONSE_SIZE 256
#define CONFIG_REMOTE_REASSEMBLY_SLOTS 2
#define CONFIG_REMOTE_REASSEMBLY_TIMEOUT_MS 500
#define CONFIG_REMOTE_REQUEST_CACHE_ENTRIES 8
#define CONFIG_HEARTBEAT_INTERVAL_MS 500
#define CONFIG_NODE_PROVISIONAL_ID 1
#define CONFIG_GPIO_RESOURCE_COUNT 8
#define CONFIG_UART_RESOURCE_COUNT 0
