#include "remotebsp/protocol/timer.hpp"
#include <stdexcept>
namespace remotebsp::protocol { namespace {
void u16(std::vector<std::uint8_t>&o,std::uint16_t v){o.push_back(v);o.push_back(v>>8U);} void u32(std::vector<std::uint8_t>&o,std::uint32_t v){for(unsigned i=0;i<4;++i)o.push_back(v>>(8U*i));} void u64(std::vector<std::uint8_t>&o,std::uint64_t v){for(unsigned i=0;i<8;++i)o.push_back(v>>(8U*i));}
std::uint16_t r16(const std::vector<std::uint8_t>&d,std::size_t p){return d[p]|(std::uint16_t(d[p+1])<<8U);} std::uint32_t r32(const std::vector<std::uint8_t>&d,std::size_t p){return r16(d,p)|(std::uint32_t(r16(d,p+2))<<16U);} std::uint64_t r64(const std::vector<std::uint8_t>&d,std::size_t p){return r32(d,p)|(std::uint64_t(r32(d,p+4))<<32U);}
std::uint16_t bit(TimerOperation o){switch(o){case TimerOperation::CounterWindow:return kTimerCapabilityCounterWindow;case TimerOperation::PeriodCapture:return kTimerCapabilityPeriodCapture;case TimerOperation::OneShot:return kTimerCapabilityOneShot;}throw std::invalid_argument("Timer操作无效");}
void valid(const TimerExecuteRequest&v){(void)bit(v.operation);if(!v.resource_id||!v.parameter_us||!v.timeout_us||v.parameter_us>kMaximumTimerOperationUs||v.timeout_us>kMaximumTimerOperationUs||v.parameter_us>v.timeout_us)throw std::invalid_argument("Timer请求超出协议边界");}
}
std::vector<std::uint8_t> encode_timer_contract(const TimerContract&v){const auto known=std::uint16_t(kTimerCapabilityCounterWindow|kTimerCapabilityPeriodCapture|kTimerCapabilityOneShot);if(v.version!=1||!v.resource_id||!v.tick_hz||!v.maximum_operation_us||v.maximum_operation_us>kMaximumTimerOperationUs||!v.capabilities||(v.capabilities&~known))throw std::invalid_argument("Timer合同无效");std::vector<std::uint8_t>o;u16(o,v.version);u16(o,v.capabilities);u32(o,v.resource_id);u32(o,v.tick_hz);u32(o,v.maximum_operation_us);return o;}
TimerContract decode_timer_contract(const std::vector<std::uint8_t>&d){if(d.size()!=16)throw std::invalid_argument("Timer合同编码无效");TimerContract v{r16(d,0),r16(d,2),r32(d,4),r32(d,8),r32(d,12)};(void)encode_timer_contract(v);return v;}
std::vector<std::uint8_t> encode_timer_execute_request(const TimerExecuteRequest&v){valid(v);std::vector<std::uint8_t>o;u32(o,v.resource_id);u16(o,static_cast<std::uint16_t>(v.operation));u16(o,0);u32(o,v.parameter_us);u32(o,v.timeout_us);return o;}
TimerExecuteRequest decode_timer_execute_request(const std::vector<std::uint8_t>&d){if(d.size()!=16||r16(d,6))throw std::invalid_argument("Timer请求编码无效");TimerExecuteRequest v{r32(d,0),static_cast<TimerOperation>(r16(d,4)),r32(d,8),r32(d,12)};valid(v);return v;}
std::vector<std::uint8_t> encode_timer_execute_result(const TimerExecuteResult&v){(void)bit(v.operation);if(!v.resource_id||!v.sequence||v.elapsed_us>kMaximumTimerOperationUs)throw std::invalid_argument("Timer结果无效");std::vector<std::uint8_t>o;u32(o,v.resource_id);u16(o,static_cast<std::uint16_t>(v.operation));u16(o,0);u32(o,v.sequence);u64(o,v.value);u32(o,v.elapsed_us);return o;}
TimerExecuteResult decode_timer_execute_result(const std::vector<std::uint8_t>&d){if(d.size()!=24||r16(d,6))throw std::invalid_argument("Timer结果编码无效");TimerExecuteResult v{r32(d,0),static_cast<TimerOperation>(r16(d,4)),r32(d,8),r64(d,12),r32(d,20)};(void)encode_timer_execute_result(v);return v;}
}
