#pragma once

#define CONFIG_REMOTE_MAX_PACKET_SIZE 1024
#define CONFIG_REMOTE_CACHE_RESPONSE_SIZE 256
#define CONFIG_REMOTE_REASSEMBLY_SLOTS 2
#define CONFIG_REMOTE_REASSEMBLY_TIMEOUT_MS 500
#define CONFIG_REMOTE_REQUEST_CACHE_ENTRIES 8
#define CONFIG_HEARTBEAT_INTERVAL_MS 500
#define CONFIG_NODE_PROVISIONAL_ID 1
#define CONFIG_GPIO_RESOURCE_COUNT 8
#define CONFIG_UART_RESOURCE_COUNT 2
#define CONFIG_UART_EVENT_CHUNK_SIZE 16
#define CONFIG_UART_EVENT_FLUSH_MS 5
