#pragma once

#define CONFIG_REMOTE_MAX_PACKET_SIZE 1024
#define CONFIG_REMOTE_CACHE_RESPONSE_SIZE 256
#define CONFIG_REMOTE_REASSEMBLY_SLOTS 2
#define CONFIG_REMOTE_REASSEMBLY_TIMEOUT_MS 500
#define CONFIG_REMOTE_REQUEST_CACHE_ENTRIES 8
#define CONFIG_HEARTBEAT_INTERVAL_MS 500
#define CONFIG_NODE_PROVISIONAL_ID 1
#define CONFIG_GPIO_RESOURCE_COUNT 8
#define CONFIG_UART_RESOURCE_COUNT 2
#define CONFIG_UART_EVENT_CHUNK_SIZE 16
#define CONFIG_UART_EVENT_FLUSH_MS 5
#define CONFIG_REMOTEBSP_PWM 1
#define CONFIG_PWM_RESOURCE_COUNT 2
#define CONFIG_PWM_MAX_FREQUENCY_HZ 100000
#define CONFIG_REMOTEBSP_TIMED_BITSTREAM 1
#define CONFIG_TIMED_BITSTREAM_RESOURCE_COUNT 1
#define CONFIG_TIMED_BITSTREAM_MAX_BITS 768
