#pragma once

/* 主机单元测试专用：在同一个 Remote Core 中覆盖全部已实现原子资源。 */
#define CONFIG_REMOTE_MAX_PACKET_SIZE 1024
#define CONFIG_REMOTE_CACHE_RESPONSE_SIZE 256
#define CONFIG_REMOTE_REASSEMBLY_SLOTS 2
#define CONFIG_REMOTE_REASSEMBLY_TIMEOUT_MS 500
#define CONFIG_REMOTE_REQUEST_CACHE_ENTRIES 8
#define CONFIG_HEARTBEAT_INTERVAL_MS 500
#define CONFIG_NODE_PROVISIONAL_ID 1
#define CONFIG_GPIO_RESOURCE_COUNT 8
#define CONFIG_UART_RESOURCE_COUNT 2
#define CONFIG_UART_EVENT_CHUNK_SIZE 16
#define CONFIG_UART_EVENT_FLUSH_MS 5
#define CONFIG_REMOTEBSP_PWM 1
#define CONFIG_PWM_RESOURCE_COUNT 2
#define CONFIG_PWM_MAX_FREQUENCY_HZ 100000
#define CONFIG_REMOTEBSP_TIMED_BITSTREAM 1
#define CONFIG_TIMED_BITSTREAM_RESOURCE_COUNT 1
#define CONFIG_TIMED_BITSTREAM_MAX_BITS 768
#define CONFIG_REMOTEBSP_MOTION 1
#define CONFIG_MOTION_MAX_AXES 4
#define CONFIG_MOTION_QUEUE_DEPTH 3
#define CONFIG_MOTION_MIN_LEAD_TIME_US 1000
#define CONFIG_MOTION_MAX_STEP_RATE_HZ 100000
#define CONFIG_MOTION_MAX_TOTAL_STEP_RATE_HZ 200000
#define CONFIG_MOTION_STEP_PULSE_WIDTH_US 2
#define CONFIG_MOTION_MIN_STEP_LOW_US 2
#define CONFIG_MOTION_DIRECTION_SETUP_US 2
#define CONFIG_MOTION_COMPARE_MIN_LEAD_US 1
#define CONFIG_MOTION_MAX_COMPARE_LATENESS_US 50
